sudo systemctl reboot
= Rootless Podman Container Fundamentals

== Overview

Podman (the POD manager) is a tool for developing, managing, and running containers on your Linux systems.

In this unit, we will get familiar with Rootless Podman containers and how to use podman, buildah and skopeo. 

== Getting Started
Exit to become student user.

[{format_cmd_exec}]
----
exit
----

ssh node3.

[{format_cmd_exec}]
----
ssh node3
----


[{format_cmd_output}]
----
# ---------------
#  Host FQDN : node3.sdcvg.internal
# OS Version : RedHat 9.1
# ---------------
Activate the web console with: systemctl enable --now cockpit.socket
----

You are now ready to proceed with these exercises.

== Core Concepts

== Exercise: Basic Information

Download podman, buildah, skopeo.

[{format_cmd_exec}]
----
sudo yum install -y buildah podman skopeo
----

[{format_cmd_output}]
----
Updating Subscription Management repositories.
Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)                                      7.3 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)                                   8.4 kB/s | 2.8 kB     00:00
Package buildah-1:1.27.3-1.el9_1.x86_64 is already installed.
Package podman-2:4.2.0-11.el9_1.x86_64 is already installed.
Package skopeo-2:1.9.4-0.1.el9_1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
----

Verify  the version of buildah.

[{format_cmd_exec}]
----
buildah --version
----

[{format_cmd_output}]
----
buildah version 1.27.3 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
----

Verify  the version of podman.

[{format_cmd_exec}]
----
podman --version
----

[{format_cmd_output}]
----
podman version 4.2.0
----

Verify  the version of skopeo.

[{format_cmd_exec}]
----
skopeo --version
----

[{format_cmd_output}]
----
skopeo version 1.9.4-dev
----


== Exercise: using podman, buildah and skopeo

=== Create an image from a container file (simple httpd web service)

Create a new container from httpd.

[{format_cmd_exec}]
----
container=$(buildah from docker.io/library/httpd:latest)
----

[{format_cmd_output}]
----
Trying to pull docker.io/library/httpd:latest...
Getting image source signatures
Copying blob ce95f18e49ae done
Copying blob 053327351b4a done
Copying blob a803e7c4b030 done
Copying blob de42e9dfbbe1 done
Copying blob 9d28e265584b done
Copying config 359570977a done
Writing manifest to image destination
Storing signatures
----

Create html directory.

[{format_cmd_exec}]
----
buildah run $container mkdir -p /usr/local/apache2/htdocs/
----

If executed successfully, won't throw any message.

Create html file.

[{format_cmd_exec}]
----
echo "<html><body><h1>Welcome to my web service</h1></body></html>" | buildah run $container tee /usr/local/apache2/htdocs/index.html
----

[{format_cmd_output}]
----
<html><body><h1>Welcome to my web service</h1></body></html>
----

Commit the changes to an image named mywebapp.

[{format_cmd_exec}]
----
buildah commit $container mywebapp
----

[{format_cmd_output}]
----
Getting image source signatures
Copying blob d310e774110a skipped: already exists
Copying blob 48b2344d5345 skipped: already exists
Copying blob 137ba5ba7d2b skipped: already exists
Copying blob 3036f5b96200 skipped: already exists
Copying blob de32a61f011b skipped: already exists
Copying blob 21fc07dce5eb done
Copying config 35e86afe15 done
Writing manifest to image destination
Storing signatures
35e86afe15b0cd5fc52f8f42d57bc1964cba4afe899c336a00f0ed5640091f01
----

=== Push to registry

User your Quay ids to login.

[{format_cmd_exec}]
----
buildah login quay.io
----

[{format_cmd_output}]
----
Username: rh_sa_bsahu
Password:
Login Succeeded!
----

Push the image to registry using "buildah push mywebapp:latest docker://quay.io/<your quay user name>/mywebapp:latest"

[{format_cmd_output}]
----
[student@node3 ~]$ buildah push mywebapp:latest docker://quay.io/rh_sa_bsahu/mywebapp:latest
Getting image source signatures
Copying blob 137ba5ba7d2b done
Copying blob d310e774110a done
Copying blob 3036f5b96200 done
Copying blob 21fc07dce5eb done
Copying blob 48b2344d5345 done
Copying blob de32a61f011b done
Copying config 35e86afe15 done
Writing manifest to image destination
Storing signatures
----

===  Create the container by pulling the image from registry

Inspect the image in the repository before pulling.

Execute skopeo inspect docker://quay.io/<your Quay userid>/mywebapp:latest

[{format_cmd_output}]
----
[student@node3 ~]$ skopeo inspect docker://quay.io/rh_sa_bsahu/mywebapp:latest|more
{
    "Name": "quay.io/rh_sa_bsahu/mywebapp",
    "Digest": "sha256:d18f4581d94c384a4c3037faeaeaad14e1cc09f84045ddccb376bc2964c980a2",
    "RepoTags": [
        "latest"
    ],
    "Created": "2023-09-20T15:15:54.914547792Z",
    "DockerVersion": "",
    "Labels": {
        "io.buildah.version": "1.27.3"
    },
   ... 
----

Pull the image from the repository.

Execute podman pull quay.io/<your Quay user id>/mywebapp:latest

[{format_cmd_output}]
----
[student@node3 ~]$ podman pull quay.io/rh_sa_bsahu/mywebapp:latest
Trying to pull quay.io/rh_sa_bsahu/mywebapp:latest...
Getting image source signatures
Copying blob cb14fc300c63 skipped: already exists
Copying blob 5ac0c08fbc05 skipped: already exists
Copying blob 079b80bd93e1 skipped: already exists
Copying blob 73c5b6af94a4 skipped: already exists
Copying blob f19d689ee9e2 skipped: already exists
Copying blob 59e1bb0f96e8 skipped: already exists
Copying config 35e86afe15 done
Writing manifest to image destination
Storing signatures
35e86afe15b0cd5fc52f8f42d57bc1964cba4afe899c336a00f0ed5640091f01
[student@node3 ~]$
----

Run it.

Execute podman run -d --name mywebapp-demo -p 8080:80 quay.io/<Your Quay user id>/mywebapp:latest

[{format_cmd_output}]
----
[student@node3 ~]$ podman run -d --name mywebapp-demo -p 8080:80 quay.io/rh_sa_bsahu/mywebapp:latest
2f022f995b92f7e225a9e303fc875b4e49c6e55b55c00fe5844069149a536df2
----

=== Check the STATUS

[{format_cmd_exec}]
----
podman ps
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE                                COMMAND           CREATED             STATUS                 PORTS
           NAMES
2f022f995b92  quay.io/rh_sa_bsahu/mywebapp:latest  httpd-foreground  About a minute ago  Up About a minute ago  0.0.0.0:808
0->80/tcp  mywebapp-demo
----

=== Check if the web service is accessible using curl

[{format_cmd_exec}]
----
curl -N localhost:8080
----

[{format_cmd_output}]
----
<html><body><h1>Welcome to my web service</h1></body></html>
----

=== Create a systemd service to get it started after system reboot automatically

Create a systemd service file to manage the `mywebapp-demo` container.

[{format_cmd_exec}]
----
mkdir -p ~/.config/systemd/user/
cd ~/.config/systemd/user
----

Create the unit file for the `mywebapp-demo` container.

[{format_cmd_exec}]
----
podman generate systemd --name mywebapp-demo --files --new
----

[{format_cmd_output}]
----
/home/student/.config/systemd/user/container-mywebapp-demo.service
----

Stop the `mywebapp-demo` container.

[{format_cmd_exec}]
----
podman stop mywebapp-demo
----

[{format_cmd_output}]
----
[student@node3 user]$ podman stop mywebapp-demo
mywebapp-demo
----

Delete the `mywebapp-demo` container.

[{format_cmd_exec}]
----
podman rm mywebapp-demo
----

[{format_cmd_output}]
----
[student@node3 user]$ podman rm mywebapp-demo
2f022f995b92f7e225a9e303fc875b4e49c6e55b55c00fe5844069149a536df2
[student@node3 user]$
----

Reload the systemd daemon configuration.

[{format_cmd_exec}]
----
systemctl --user daemon-reload
----

Enable and start your new `container-mywebapp-demo` user service.

[{format_cmd_exec}]
----
systemctl --user enable --now container-mywebapp-demo
----

[{format_cmd_output}]
----
[student@node3 user]$ systemctl --user enable --now container-mywebapp-demo
Created symlink /home/student/.config/systemd/user/default.target.wants/container-mywebapp-demo.service → /home/student/.co
nfig/systemd/user/container-mywebapp-demo.service.
----

Verify that the web server responds to requests.

[{format_cmd_exec}]
----
curl http://localhost:8080
----

[{format_cmd_output}]
----
<html><body><h1>Welcome to my web service</h1></body></html>
----

Verify that the container is running.

[{format_cmd_exec}]
----
podman ps
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE                                COMMAND           CREATED             STATUS                 PORTS
           NAMES
3e311ea3f138  quay.io/rh_sa_bsahu/mywebapp:latest  httpd-foreground  About a minute ago  Up About a minute ago  0.0.0.0:808
0->80/tcp  mywebapp-demo
----

Use the container ID information to confirm that the systemd daemon creates a container when you restart the service.

[{format_cmd_exec}]
----
systemctl --user stop container-mywebapp-demo
----

[{format_cmd_exec}]
----
podman ps --all
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
----

[{format_cmd_exec}]
----
systemctl --user start container-mywebapp-demo
----

[{format_cmd_exec}]
----
podman ps
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE                                COMMAND           CREATED         STATUS             PORTS
   NAMES
36f9a4037896  quay.io/rh_sa_bsahu/mywebapp:latest  httpd-foreground  39 seconds ago  Up 39 seconds ago  0.0.0.0:8080->80/tc
p  mywebapp-demo
----

Ensure that the services for your user start at system boot, then restart your machine.

[{format_cmd_exec}]
----
loginctl enable-linger
----

[{format_cmd_exec}]
----
oginctl show-user student
----

[{format_cmd_output}]
----
[student@node3 user]$ loginctl show-user student
UID=1001
GID=1001
Name=student
Timestamp=Wed 2023-09-20 15:01:59 UTC
TimestampMonotonic=73932449066
RuntimePath=/run/user/1001
Service=user@1001.service
Slice=user-1001.slice
Display=18
State=active
Sessions=18
IdleHint=no
IdleSinceHint=1695225427284535
IdleSinceHintMonotonic=77239965832
Linger=yes
----

{format_cmd_exec}]
----
sudo systemctl reboot
----

[{format_cmd_output}]
----
Connection to node3 closed.
----

Log back in and verify that the systemd daemon started the `mywebapp-demo` container, and that the web content is available.

{format_cmd_exec}]
----
ssh node3
----

[{format_cmd_output}]
----
# ---------------
#  Host FQDN : node3.sdcvg.internal
# OS Version : RedHat 9.1
# ---------------
Web console: https://node3.sdcvg.internal:9090/ or https://192.168.0.168:9090/

Last login: Wed Sep 20 15:02:00 2023 from 192.168.0.147
----

[{format_cmd_exec}]
----
podman ps
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE                                COMMAND           CREATED             STATUS                 PORTS
           NAMES
d9773e176ba8  quay.io/rh_sa_bsahu/mywebapp:latest  httpd-foreground  About a minute ago  Up About a minute ago  0.0.0.0:808
0->80/tcp  mywebapp-demo
----

[{format_cmd_exec}]
----
curl http://localhost:8080
----

[{format_cmd_output}]
----
<html><body><h1>Welcome to my web service</h1></body></html>
----

Done!

=== Cleanup exercise

[{format_cmd_exec}]
----
podman rm -af
----

[{format_cmd_output}]
----
d9773e176ba8eb914876de20cee53a792a9e88dbd0e48c2201167b87f2a4a29c
----

[{format_cmd_exec}]
----
podman rmi -af
----

[{format_cmd_output}]
----
Untagged: docker.io/library/httpd:latest
Untagged: quay.io/rh_sa_bsahu/mywebapp:latest
Untagged: localhost/mywebapp:latest
Deleted: 35e86afe15b0cd5fc52f8f42d57bc1964cba4afe899c336a00f0ed5640091f01
----

Check to see if any process running:

[{format_cmd_exec}]
----
podman ps
----

[{format_cmd_output}]
----
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
----

[{format_cmd_exec}]
----
pkill -9 -u student
----

[{format_cmd_output}]
----
Connection to node3 closed by remote host.
Connection to node3 closed.
----

















